### ISSUE TITLE
Wrong definition of X2C

### ISSUE THREAD

**Issue by daharn** [DENG-MIT/Arrhenius.jl#82]
The current equation for `X2C(gas, X, ρ_mass)`
```julia
C = X * ρ_mass ./ gas.MW
```
seems incorrect to me. It is the same as for `Y2C`, which can't be the case. 
Instead it should read
```julia
C = X * ρ_mass / sum(X.*gas.MW)
```

**Comment by jiweiqi** [comment]
hi @daharn good spot. I think you are right. And feel free to pull a request for that.
In my own project, I only used Y2C so far, so that I haven't really used X2C in the past. A placeholder was put there for X2C.
